function init() {
	headerFunction();
	subHeaderFunction();
	logoHeader();
	bodyFunction();
	buttons();
	containerWps();
	bannersComponent();
	eventsLists();
	raceEvents();
	searchLists();
	forms();
	scrollText();
	tabsComponent();
	tables();
	carousel();
	panelsBox();
	footer();
	setIe10();
}